alias pdf="zathura"
alias p="sudo pacman"
alias ls="exa --icons"
alias l="exa --icons -la"
alias ra="ranger"
alias vim="nvim"
alias gt="git log --graph --decorate --pretty=oneline --abbrev-commit"
alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias gaa="git add --all"
alias gd="git diff"
alias gp="git push"
alias selfie="mpv av://v4l2:/dev/video0 --profile=low-latency --untimed"
alias source-zsh="source $XDG_CONFIG_HOME/zsh/.zshrc"
alias scrotcp="scrot '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f'"
