#!/bin/sh

bspc config border_width 8
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focused_border_color "#424242"
bspc config normal_border_color "#424242"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

[ "$HOSTNAME" = "$LAPTOP" ] && [ "$(xrandr -q | grep ' connected' | wc -l)" -ge 2 ] && bspc monitor DP1 -d 1 2 3 4 5 && bspc monitor eDP1 -d 6 7 8 9 0 || [ "$HOSTNAME" = "$LAPTOP" ] && bspc monitor -d 1 2 3 4 5 6 7 8 9 0
[ "$HOSTNAME" = "$PC" ] && bspc monitor DP-4 -d 1 2 3 4 5 && bspc monitor DP-2 -d 6 7 8 9
wm-borders &
